# Generated by Django 3.0.3 on 2020-02-16 17:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_auto_20200216_1714'),
        ('money', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MoneyPrice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price_type', models.CharField(max_length=256)),
                ('price', models.FloatField()),
                ('money', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='money.Money')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.User')),
            ],
        ),
    ]
