# Generated by Django 3.0.3 on 2020-02-15 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('open_id', models.CharField(max_length=64, unique=True)),
                ('nickname', models.CharField(db_index=True, max_length=256)),
                ('focus_cities', models.TextField(default='[]')),
            ],
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['open_id'], name='user_user_open_id_838a98_idx'),
        ),
    ]
